try:
    pass
except ValueError as e:
    pass
else:
    pass
finally:
    pass