with open('my_file.txt', 'z'):  # Error on this line
    pass
